# This baby takes care of making sure a number
# of todod pods are always provisioned and running
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todod-deploy
  namespace: todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todod
  template:
    metadata:
      labels:
        app: todod
    spec:
      containers:
        # This is the todod Pod
        - name: todod-pod
          image: 192.168.0.11:5000/k8s-lab/todod:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 128Mi
              cpu: 100m
