# This baby takes care of making sure a number
# of todod pods are always provisioned and running
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todod-deploy
  namespace: k8s-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todod
  template:
    metadata:
      labels:
        app: todod
    spec:
      containers:
        # This is the todod Pod
        - name: todod
          image: k8s-lab/todod:latest
          # Since the todod container image
          # gets built inside minikube's docker daemon
          # then, we need to make sure that this cluster
          # takes the local image everytime
          # source:
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: 64Mi
              cpu: 10m
