# A Service represents a single entrypoint in the cluster
# acting as a "service", in the background it proxies all
# traffic to pods whose labels match its selector field
apiVersion: v1
kind: Service
metadata:
  name: todod-svc
  namespace: todo
spec:
  selector:
    app: todod-pod
  type: NodePort
  ports:
    - name: todod-svc
      port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 30800
