#!/usr/bin/env bash
# This script installs the NGINX Ingress Controller on a Kubernetes cluster.
# and configures it to use MetalLB for load balancing.
set -e

# Install the Ingress controller (nginx)
# ------------------------------------
helm upgrade --install ingress-nginx ingress-nginx \
--repo https://kubernetes.github.io/ingress-nginx \
--namespace ingress-nginx --create-namespace

# Install MetalLB (load balancer)
# ------------------------------------
# If you’re using kube-proxy in IPVS mode, since Kubernetes v1.14.2 you have to enable strict ARP mode.
# source: https://metallb.universe.tf/installation/#preparation
kubectl get configmap kube-proxy -n kube-system -o yaml | \
sed -e "s/strictARP: false/strictARP: true/" | \
kubectl apply -f - -n kube-system

# Actually install MetalLB (via Helm)
helm upgrade --install metallb metallb \
--repo https://metallb.github.io/metallb \
--namespace metallb-system --create-namespace \
--wait --timeout 5m0s

# Configure MetalLB
j2 /vagrant/config.yaml /vagrant/files/remote/k8s/metallb-config.yaml.j2 > /vagrant/files/remote/k8s/metallb-config.yaml
kubectl apply -f /vagrant/files/remote/k8s/metallb-config.yaml
