# FIXME: doc me
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
  namespace: k8s-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: hello-ctr
          image: nigelpoulton/k8sbook:latest
          containerPort: 8080
