# FIXME: doc me
apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
  namespace: k8s-lab
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
      targetPort: 8080
      protocol: TCP
  selector:
    app: httpd
