# HTTP endpoint tests for REST client
# humao.rest-client
# -----------------------------------

@base_url=http://localhost:8000


#  TODO list
#####################

# Get todo list
GET {{base_url}}/todolist


###


# Post new TODO
POST {{base_url}}/todolist/task
Content-Type: application/json

{
  "message": "fare la spesa"
}
