# HTTP endpoint tests for REST client
# humao.rest-client
# -----------------------------------

# Variables
@baseUrl = http://{{hostName}}:{{hostPort}}


#  TODO list
#####################

# Get todo list
GET {{baseUrl}}/todolist


###


# Post new TODO task
POST {{baseUrl}}/todolist/task
Content-Type: application/json

{
  "message": "fare la spesa"
}

###

# GET TODO task
GET {{baseUrl}}/todolist/task
