# -----------------------------------------------------
# This ClusterRoleBinding grants the 'cluster-admin' ClusterRole to the user 'k8s-lab-admin'.
# - apiVersion: Specifies the RBAC API version.
# - kind: Defines this resource as a ClusterRoleBinding, which binds a ClusterRole to users, groups, or service accounts at the cluster level.
# - metadata.name: The name of this ClusterRoleBinding resource.
# - subjects: Lists the entities (in this case, a User named 'k8s-lab-admin') that are granted the permissions.
# - roleRef: References the ClusterRole ('cluster-admin') that is being granted to the subject.
# This binding gives 'k8s-lab-admin' full administrative privileges across the entire Kubernetes cluster.
# -----------------------------------------------------

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-lab-admin-binding
subjects:
  - kind: User
    name: k8s-lab-admin
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
